
[build]
builder = "NIXPACKS"
buildCommand = "cd backend/EcommerceApi && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd backend/EcommerceApi/out && dotnet EcommerceApi.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10